builds:
  - main: ./cmd/demo/main.go
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - darwin
      - linux
      - windows
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto